# Generated by Django 5.2.6 on 2025-10-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.IntegerField(max_length=200)),
                ('lon', models.IntegerField(max_length=200)),
            ],
        ),
    ]
